Description: >
  Shahzeb Anwar /  Udacity DepOps Project 2 (Udagram App)
  This is the second project of Udacity DevOps Nanodegre Program which 
  involves the deployment of Cloud Infrastructure for High Availability
  WebApp called Udagram

	This file defines the infrastructure configuration required for the APP

Parameters:

  EnvironmentName: UdagramApp
  Type: String

  VpcCIDR: 
		Description: Please enter the IP range (CIDR notation) for this VPC
		Type: String
		Default: 10.0.0.0/16

		PublicSubnet1CIDR:
			Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
			Type: String
			Default: 10.0.0.0/24

		PublicSubnet2CIDR:
			Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
			Type: String
			Default: 10.0.1.0/24

		PrivateSubnet1CIDR:
			Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
			Type: String
			Default: 10.0.2.0/24

		PrivateSubnet2CIDR:
			Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
			Type: String
			Default: 10.0.3.0/24
					
Resources:

	VPC: 
		Type: AWS::EC2::VPC
		Properties:
			CidrBlock: !Ref VpcCIDR
			EnableDnsHostnames: true
			Tags: 
				- Key: Name 
					Value: !Ref EnvironmentName

	InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref ProjectName
	
	InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
	
	 PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} Public Subnet 1 (AZ1)
  
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} Public Subnet 2 (AZ2)
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} Private Subnet 1 (AZ1)
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
					Value: !Sub ${ProjectName} Private Subnet 2 (AZ2)
					
	NatGateway1EIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAttachment
    Properties:
      Domain: "vpc"
  
  NatGateway2EIP:
      Type: AWS::EC2::EIP
      DependsOn: InternetGatewayAttachment
      Properties:
        Domain: "vpc"
  
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} NAT Gateway 1 (AZ1)
  
  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
					Value: !Sub ${ProjectName} NAT Gateway 2 (AZ1)
					
	PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName} Public Route Table